created(1630398590.74544).
assert(fact(pessoa(6))).
assert(fact(pessoa(7))).
assert(fact(pessoa(8))).
assert(fact(pessoa(9))).
assert(fact(pessoa(10))).
assert(fact(aluno(6))).
assert(fact(aluno(7))).
assert(fact(aluno(8))).
assert(fact(aluno(9))).
assert(fact(aluno(10))).
assert(fact(aluno_nome(6,"gustavo"))).
assert(fact(aluno_nome(7,"marina"))).
assert(fact(aluno_nome(8,"otavio"))).
assert(fact(aluno_nome(9,"lucas"))).
assert(fact(aluno_nome(10,"matheus"))).
assert(fact(aluno_turma(6,"software"))).
assert(fact(aluno_turma(7,"software"))).
assert(fact(aluno_turma(8,"software"))).
assert(fact(aluno_turma(9,"software"))).
assert(fact(aluno_turma(10,"software"))).
assert(fact(aluno_semestre(6,8))).
assert(fact(aluno_semestre(7,8))).
assert(fact(aluno_semestre(8,8))).
assert(fact(aluno_semestre(9,8))).
assert(fact(aluno_semestre(10,8))).
assert(fact(aluno_transporte(6,"onibus"))).
assert(fact(aluno_transporte(7,"carro"))).
assert(fact(aluno_transporte(8,"onibus"))).
assert(fact(aluno_transporte(9,"van"))).
assert(fact(aluno_transporte(10,"onibus"))).
assert(fact(aluno_cidade(6,"Vargem"))).
assert(fact(aluno_cidade(7,"Vargem"))).
assert(fact(aluno_cidade(8,"SJBV"))).
assert(fact(aluno_cidade(9,"Águas da Prata"))).
assert(fact(aluno_cidade(10,"SJBV"))).
assert(fact(pessoa(1))).
assert(fact(pessoa(2))).
assert(fact(pessoa(3))).
assert(fact(pessoa(4))).
assert(fact(pessoa(5))).
assert(fact(professor(1))).
assert(fact(professor(2))).
assert(fact(professor(3))).
assert(fact(professor(4))).
assert(fact(professor(5))).
assert(fact(professor_nome(1,"cristiane"))).
assert(fact(professor_nome(2,"adriana"))).
assert(fact(professor_nome(3,"patricia"))).
assert(fact(professor_nome(4,"luciana"))).
assert(fact(professor_nome(5,"claudete"))).
assert(fact(professor_turma(1,"software"))).
assert(fact(professor_turma(2,"software"))).
assert(fact(professor_turma(3,"software"))).
assert(fact(professor_turma(4,"software"))).
assert(fact(professor_turma(5,"software"))).
assert(fact(professor_semestre(1,8))).
assert(fact(professor_semestre(2,8))).
assert(fact(professor_semestre(3,8))).
assert(fact(professor_semestre(4,8))).
assert(fact(professor_semestre(5,8))).
assert(fact(professor_transporte(1,"carro_compartilhado"))).
assert(fact(professor_transporte(2,"carro"))).
assert(fact(professor_transporte(3,"carro"))).
assert(fact(professor_transporte(4,"carro"))).
assert(fact(professor_transporte(5,"carro_compartilhado"))).
assert(fact(professor_cidade(1,"Paulinia"))).
assert(fact(professor_cidade(2,"SJBV"))).
assert(fact(professor_cidade(3,"Pinhal"))).
assert(fact(professor_cidade(4,"SJBV"))).
assert(fact(professor_cidade(5,"Poços"))).
assert(fact(confirmado(1))).
assert(fact(confirmado(6))).
assert(fact(suspeito(2))).
assert(fact(suspeito(7))).
assert(fact(morte(3))).
assert(fact(morte(8))).
assert(fact(parente(6,8))).
assert(fact(parente(8,6))).
assert(fact(parente(6,7))).
assert(fact(parente(7,6))).
assert(fact(parente(1,2))).
assert(fact(parente(2,1))).
assert(fact(parente(1,3))).
assert(fact(parente(3,1))).
